### ISSUE TITLE
Curl报错500 Internal Server Error

### ISSUE THREAD

**Issue by Lightmani** [sfpprxy/portmon#7]
安装环境：Centos 7  通过GIT拉取项目
步骤：
1、拉取文件，添加权限
2、修改ini文件中的端口，执行安装
3、curl localhost:9000

奇怪的是只要我不修改默认监视端口（22和9000）就不会出现这个错误，但我修改了ini文件中的监视端口后就会报错。

报错内容：
# curl localhost:9000

    <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
    <html>
        <head>
            <title>Error: 500 Internal Server Error</title>
            <style type="text/css">
              html {background-color: #eee; font-family: sans-serif;}
              body {background-color: #fff; border: 1px solid #ddd;
                    padding: 15px; margin: 15px;}
              pre {background-color: #eee; border: 1px solid #ddd; padding: 5px;}
            </style>
        </head>
        <body>
            <h1>Error: 500 Internal Server Error</h1>
            <p>Sorry, the requested URL <tt>&#039;http://localhost:9000/&#039;</tt>
               caused an error:</p>
            <pre>Internal Server Error</pre>
        </body>
    </html>

日志文件：
2020-07-22 05:22:02,998 [MainThread  ] {/usr/bin/portmon.py:153} [INFO ]  get_statistic of
2020-07-22 05:22:18,710 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10', '1'}
2020-07-22 05:22:18,724 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '9000': 0}
2020-07-22 05:22:18,725 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '9000': 0}
2020-07-22 05:23:18,793 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10', '1'}
2020-07-22 05:23:18,807 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '9000': 0}
2020-07-22 05:23:18,808 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '9000': 0}
2020-07-22 05:24:18,879 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10', '1'}
2020-07-22 05:24:18,891 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '9000': 0}
2020-07-22 05:24:18,892 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '9000': 0}
2020-07-22 05:25:18,961 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10', '1'}
2020-07-22 05:25:18,971 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '9000': 0}
2020-07-22 05:25:18,972 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '9000': 0}

**Comment by Lightmani** [comment]
直接运行/usr/bin/python3 /usr/bin/portmon.py后，发现每次curl后，会如下报错

 ```
Listening on http://0.0.0.0:9000/
Hit Ctrl-C to quit.

2020-07-22 07:25:19,776 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10', '1'}
2020-07-22 07:25:19,785 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '9000': 0}
2020-07-22 07:25:19,786 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '9000': 0}
2020-07-22 07:25:52,866 [MainThread  ] {/usr/bin/portmon.py:153} [INFO ]  get_statistic of 
Traceback (most recent call last):
  File "/usr/bin/bottle/bottle.py", line 1005, in _handle
    out = route.call(**args)
  File "/usr/bin/bottle/bottle.py", line 2017, in wrapper
    rv = callback(*a, **ka)
  File "/usr/bin/portmon.py", line 185, in index
    return get_statistic('')
  File "/usr/bin/portmon.py", line 158, in get_statistic
    b = usage_disk[p]
KeyError: '1'
127.0.0.1 - - [22/Jul/2020 07:25:52] "GET / HTTP/1.1" 500 747

```

**Comment by Lightmani** [comment]
多次测试后发现，~/.portmon/portmon.ini中的监听端口只在仅为初始值22和9000时不会报错
改成其他任何值（比如10111），均会报错
Jul 22 07:34:13 VM-4705 python3[8914]: File "/usr/bin/portmon.py", line 158, in get_statistic
Jul 22 07:34:13 VM-4705 python3[8914]: b = usage_disk[p]
Jul 22 07:34:13 VM-4705 python3[8914]: KeyError: '10111'

**Comment by sfpprxy** [comment]
我在centos7上按照你的步骤，无法复现问题。下面是我的操作日志，请问我们的操作步骤一样吗？
```
[root@vultr portmon]# vi portmon.ini
[root@vultr portmon]# chmod +x install.sh
[root@vultr portmon]# ./install.sh
[root@vultr portmon]# cat ~/.portmon/portmon.ini
[DEFAULT]
serve_port = 9000
monitor_ports = 22,10111
[root@vultr portmon]# curl localhost:9000
Port 22 data usage: 0KB = 0.0GB => Bill: 0.0RMB
Port 10111 data usage: 0KB = 0.0GB => Bill: 0.0RMB
[root@vultr portmon]# cat ~/.portmon/portmon.log
2020-07-23 03:28:30,697 [MainThread  ] {/usr/bin/portmon.py:39} [INFO ]  config path: /root/.portmon/portmon.ini
2020-07-23 03:28:30,697 [MainThread  ] {/usr/bin/portmon.py:58} [DEBUG]  no data file
2020-07-23 03:28:30,814 [TrafficMonit] {/usr/bin/portmon.py:115} [DEBUG]  {'10111', '22'}
2020-07-23 03:28:30,821 [TrafficMonit] {/usr/bin/portmon.py:126} [DEBUG]  init usage_disk{'22': 0, '10111': 0}
2020-07-23 03:28:30,821 [TrafficMonit] {/usr/bin/portmon.py:141} [DEBUG]  {'22': 0, '10111': 0}
2020-07-23 03:29:12,326 [MainThread  ] {/usr/bin/portmon.py:153} [INFO ]  get_statistic of
2020-07-23 03:29:12,327 [MainThread  ] {/usr/bin/portmon.py:163} [INFO ]  Port 22 data usage: 0KB = 0.0GB => Bill: 0.0RMB
Port 10111 data usage: 0KB = 0.0GB => Bill: 0.0RMB

```

**Comment by Lightmani** [comment]
我们的操作步骤是一样的. 
不过,在我将内核升级至最新的5.7后,这个问题解决了,可以正常运行.
但是我最开始在3.10的内核下,一直是报错的.

**Comment by sfpprxy** [comment]
> 我们的操作步骤是一样的.
> 不过,在我将内核升级至最新的5.7后,这个问题解决了,可以正常运行.
> 但是我最开始在3.10的内核下,一直是报错的.

[root@vultr ~]# uname -a
Linux vultr.guest 3.10.0-1127.13.1.el7.x86_64

我测试环境的3.10.0-1127.13.1.el7.x86_64内核未能复现。如果有问题欢迎reopen issue。

**Comment by qjfoidnh** [comment]
3.10.0-1127.el7.x86_64内核和5.4.0-42-generic均已复现该问题。
出现条件：
    服务启动状态下修改ini文件增加端口且修改后以service restart/systemctl restart方式重启服务
不会出现问题的情况：
1. 修改后不重启服务，此时配置文件没有重新加载，curl新增端口将返回原配置文件中的所有端口状态
2. 分stop -> start两步方式重启服务，curl可正常监视到新增端口

**Comment by sfpprxy** [comment]
> 3.10.0-1127.el7.x86_64内核和5.4.0-42-generic均已复现该问题。
> 出现条件：
> 服务启动状态下修改ini文件增加端口且修改后以service restart/systemctl restart方式重启服务
> 不会出现问题的情况：
> 
> 1. 修改后不重启服务，此时配置文件没有重新加载，curl新增端口将返回原配置文件中的所有端口状态
> 2. 分stop -> start两步方式重启服务，curl可正常监视到新增端口

可以复现，是程序的问题内核无关。该问题出现在修改配置后第一次启动程序时，操作2. 可正常curl到应该是你之前已经重启过程序了，若修改配置直接按 2. 操作问题可以复现。

8151bdd389a2eada92477bda41d8f7f763cb2102 已修复。
